import React,{useState} from "react";
import {ArrowRight,BrainCircuit,Check,ChevronRight,Play,RotateCcw,Sparkles,Zap} from "lucide-react";
import AppShell from "../components/layout/AppShell";
import {Link} from "react-router-dom";
import {learningProfile} from "../data/mock";

const demo=[
 {title:"Student action",text:"A sample learner answers concept questions correctly, then misses an application question.",icon:Check},
 {title:"AI understanding",text:"ADAPT detects a gap in application/problem solving while conceptual understanding remains strong.",icon:BrainCircuit},
 {title:"AI decision",text:"Difficulty steps down, explanation style switches to an example-first approach, and the weak topic becomes the priority.",icon:Zap},
 {title:"Personalized result",text:"The next question is targeted to the misconception and the learner sees why it was selected.",icon:Sparkles}
];

export default function HackathonLab(){const [step,setStep]=useState(0);const [running,setRunning]=useState(false);const current=demo[step];const Icon=current.icon;
 const run=()=>{setRunning(true);setStep(0);let i=0;const timer=setInterval(()=>{i++;if(i>=demo.length){clearInterval(timer);setRunning(false);return}setStep(i)},1100)};
 return <AppShell breadcrumb="ADAPT LAB"><div className="page"><div className="eyebrow">HACKATHON SHOWCASE</div><h1 className="page-title" style={{marginTop:8}}>Watch ADAPT adapt.</h1><p className="page-subtitle">A live visual story of <b>student action → AI understanding → AI decision → personalized result.</b></p>
 <div className="insight" style={{marginTop:18}}><div className="mini">SIMULATED DEMO · This visualization uses illustrative learner data and does not represent your saved progress.</div></div>
 <div className="lab-grid" style={{marginTop:12}}><section className="card card-pad hero-panel"><div style={{display:"flex",justifyContent:"space-between",alignItems:"center"}}><div><div className="eyebrow">ADAPT LEARNING TWIN</div><h2 style={{fontSize:24,marginTop:7}}>The model changes as you learn.</h2></div><button className="btn btn-primary" onClick={run} disabled={running}><Play size={14}/>{running?"ADAPT IS LEARNING...":"Run adaptation demo"}</button></div><div className="twin" style={{marginTop:30}}><div className="twin-core"><div style={{textAlign:"center"}}><div className="twin-score">{learningProfile.overallScore+step}</div><div className="tiny">DEMO SCORE</div></div></div><div><div className="decision-stack">{demo.map((d,i)=>{const D=d.icon;return <div className="decision-row" key={d.title} style={{opacity:i===step?1:.55,borderColor:i===step?"rgba(155,92,255,.65)":"var(--border)"}}><span className={`signal-dot ${i<step?"success":""}`}/><div><div style={{fontSize:11,fontWeight:800}}>{d.title}</div><div className="mini" style={{marginTop:3,lineHeight:1.5}}>{d.text}</div></div><D size={14} color={i===step?"var(--lavender)":"var(--muted)"}/></div>})}</div></div></div></section>
 <aside className="card card-pad"><div className="eyebrow">CURRENT AI DECISION</div><div style={{marginTop:20,width:48,height:48,borderRadius:15,display:"grid",placeItems:"center",background:"rgba(124,60,255,.13)",border:"1px solid rgba(155,92,255,.3)"}}><Icon size={21} color="var(--lavender)"/></div><h2 style={{fontSize:22,marginTop:14}}>{current.title}</h2><p className="mini" style={{lineHeight:1.7,marginTop:7}}>{current.text}</p><div className="insight" style={{marginTop:18}}><Sparkles size={15}/><div className="mini">Why it matters: ADAPT does not only score the learner; it uses the signal to change what comes next.</div></div></aside></div>
 <div className="grid grid-3" style={{marginTop:16}}><div className="card card-pad"><div className="eyebrow">LEARNING DNA</div><h3 style={{marginTop:7}}>Know the learner.</h3><p className="mini" style={{marginTop:7,lineHeight:1.6}}>Mastery, pace, recall, application and explanation preferences.</p><Link className="btn" style={{marginTop:15}} to="/learning-dna">Open Learning DNA <ArrowRight size={14}/></Link></div><div className="card card-pad"><div className="eyebrow">WHY THIS QUESTION?</div><h3 style={{marginTop:7}}>Make the decision visible.</h3><p className="mini" style={{marginTop:7,lineHeight:1.6}}>Every practice question exposes the learner signal behind the recommendation.</p><Link className="btn" style={{marginTop:15}} to="/practice">Try Adaptive Practice <ArrowRight size={14}/></Link></div><div className="card card-pad"><div className="eyebrow">AI VOICE</div><h3 style={{marginTop:7}}>Talk, interrupt, learn.</h3><p className="mini" style={{marginTop:7,lineHeight:1.6}}>The voice experience uses the same learner context.</p><Link className="btn" style={{marginTop:15}} to="/voice">Open Voice AI <ArrowRight size={14}/></Link></div></div>
 <div style={{display:"flex",justifyContent:"flex-end",marginTop:14}}><button className="btn" onClick={()=>setStep(0)}><RotateCcw size={14}/> Reset demo</button></div>
 </div></AppShell>}
