import React, { useEffect, useState } from "react";
import { AlertTriangle, Check, Cloud, Cpu, Eye, EyeOff, KeyRound, LockKeyhole, ShieldAlert, Trash2, TriangleAlert } from "lucide-react";
import AppShell from "../components/layout/AppShell";
import { BYOK_PROVIDERS, BYOK_PROVIDER, getByokStatus, removeByokCredential, validateProviderCredential } from "../services/byokSettings";
import { getTutorMode, subscribeTutorMode } from "../services/tutorMode";

function formatCheckedAt(value) {
  if (!value) return "";
  const date = new Date(value);
  return Number.isNaN(date.getTime()) ? "" : date.toLocaleString();
}

export default function Settings() {
  const [credential, setCredential] = useState(() => getByokStatus(undefined, undefined, BYOK_PROVIDER.id));
  const [provider, setProvider] = useState(BYOK_PROVIDER.id);
  const [draft, setDraft] = useState("");
  const [revealed, setRevealed] = useState(false);
  const [editing, setEditing] = useState(() => !getByokStatus(undefined, undefined, BYOK_PROVIDER.id).configured);
  const [consent, setConsent] = useState(false);
  const [checking, setChecking] = useState(false);
  const [validation, setValidation] = useState(null);
  const [activeMode, setActiveMode] = useState(getTutorMode);
  const [removeError, setRemoveError] = useState("");

  useEffect(() => subscribeTutorMode(setActiveMode), []);

  const providerInfo = BYOK_PROVIDERS.find((item) => item.id === provider) || BYOK_PROVIDER;

  const selectProvider = (nextProvider) => {
    setProvider(nextProvider);
    const nextCredential = getByokStatus(undefined, undefined, nextProvider);
    setCredential(nextCredential);
    setDraft("");
    setConsent(false);
    setValidation(null);
    setEditing(!nextCredential.configured);
    setRevealed(false);
  };

  const validate = async () => {
    if (!consent) {
      setValidation({ kind: "consent", message: "Review and accept the key handling notice before validation and local storage." });
      return;
    }
    setChecking(true);
    setValidation({ kind: "checking", message: "Checking the key directly with Google…" });
    const result = await validateProviderCredential(provider, draft);
    setChecking(false);
    setValidation(result);
    if (result.ok) {
      setCredential(getByokStatus(undefined, undefined, provider));
      setDraft("");
      setEditing(false);
      setConsent(false);
      setRevealed(false);
    }
  };

  const beginChange = () => {
    setDraft("");
    setConsent(false);
    setValidation(null);
    setEditing(true);
  };

  const remove = () => {
    setRemoveError("");
    if (!removeByokCredential(undefined, undefined, provider)) {
      setRemoveError("Browser storage could not remove the saved key. Check this browser's storage settings.");
      return;
    }
    setCredential(getByokStatus(undefined, undefined, provider));
    setDraft("");
    setConsent(false);
    setValidation({ kind: "removed", message: "The saved key was removed from this browser." });
    setEditing(true);
  };

  const validationClass = validation?.ok || validation?.kind === "removed" ? "byok-result success" : validation?.kind === "checking" ? "byok-result checking" : validation ? "byok-result failure" : "";

  return <AppShell breadcrumb="SETTINGS"><div className="page settings-page">
    <div className="eyebrow">PREFERENCES &amp; SECURITY</div>
    <h1 className="page-title" style={{ marginTop: 8 }}>AI settings</h1>
    <p className="page-subtitle">Manage an optional provider credential and see which Tutor mode is active.</p>

    <section className="card byok-mode-card" style={{ marginTop: 24 }} aria-label="Current Tutor mode">
      <div className="byok-mode-icon">{activeMode === "local" ? <Cpu size={18} /> : <Cloud size={18} />}</div>
      <div className="byok-mode-copy">
        <div className="eyebrow">ACTIVE TUTOR MODE</div>
        <strong>{activeMode === "local" ? "Local AI · On this device" : "Hosted AI · ADAPT server"}</strong>
        <span>{activeMode === "local" ? "Tutor replies are generated by the downloaded on-device model." : "Tutor replies use ADAPT's existing hosted service."}</span>
      </div>
      <span className={`badge ${activeMode === "local" ? "success" : ""}`}>{activeMode === "local" ? "LOCAL" : "HOSTED"}</span>
    </section>

    <div className="byok-layout" style={{ marginTop: 16 }}>
      <section className="card card-pad byok-card">
        <div className="byok-card-heading">
          <div className="byok-heading-icon"><KeyRound size={17} /></div>
          <div><div className="eyebrow">OPTIONAL CREDENTIAL</div><h2 style={{ fontSize: 21, marginTop: 5 }}>Bring your own API key</h2></div>
        </div>
        <p className="mini byok-intro">Choose a provider and verify its credential. Your saved key stays in this browser and is not connected to Tutor responses.</p>

        <label className="byok-label" htmlFor="byok-provider">Selected provider</label>
        <select id="byok-provider" className="byok-control" value={provider} onChange={(event) => selectProvider(event.target.value)} disabled={checking}>
          {BYOK_PROVIDERS.map((item) => <option key={item.id} value={item.id}>{item.label}</option>)}
        </select>
        <div className="byok-provider-caption">Keys are stored separately for each provider and learner.</div>

        {credential.configured && !editing && <div className="byok-saved">
          <div className="byok-saved-main"><span className="byok-saved-check"><Check size={14} /></span><div><strong>{providerInfo.label} key validated</strong><span>{credential.checkedAt ? `Last checked ${formatCheckedAt(credential.checkedAt)}` : "Previously validated"}</span></div></div>
          <span className="badge success">VALIDATED</span>
        </div>}

        {editing && <>
          <label className="byok-label" htmlFor="byok-api-key">{credential.configured ? "Replacement API key" : `${providerInfo.label} API key`}</label>
          <div className="byok-input-wrap">
            <input id="byok-api-key" className="byok-control byok-key-input" type={revealed ? "text" : "password"} value={draft} onChange={(event) => { setDraft(event.target.value); setValidation(null); }} autoComplete="off" spellCheck="false" placeholder={`Paste your ${providerInfo.label} API key`} disabled={checking} />
            <button type="button" className="byok-reveal" onClick={() => setRevealed((value) => !value)} aria-label={revealed ? "Hide API key" : "Show API key"} title={revealed ? "Hide key" : "Show key"}><span className="sr-only">{revealed ? "Hide key" : "Show key"}</span>{revealed ? <EyeOff size={16} /> : <Eye size={16} />}</button>
          </div>
          <div className="byok-consent">
            <div className="byok-consent-title"><ShieldAlert size={15} /> Before you save</div>
            <p>Validation sends the key directly to {providerInfo.label} in a request header. {providerInfo.securityWarning} The key is stored unencrypted in this browser's local storage, where this site's scripts, browser extensions, or someone with access to this browser profile may read it. Use a restricted key on a device you control. <a href={providerInfo.securityUrl} target="_blank" rel="noreferrer">{providerInfo.label} key security guidance</a></p>
            <p>The selected provider receives the validation request, not your Tutor prompts. Provider data terms and quotas apply; paid generation can incur charges. Review the provider's <a href={providerInfo.termsUrl} target="_blank" rel="noreferrer">data terms</a> and <a href={providerInfo.billingUrl} target="_blank" rel="noreferrer">billing details</a>. This key is for validation only and does not power Tutor.</p>
            <label className="byok-consent-check"><input type="checkbox" checked={consent} onChange={(event) => setConsent(event.target.checked)} disabled={checking} /><span>I understand where the key is sent and stored, and that it will not be used for Tutor responses.</span></label>
          </div>
          <div className="byok-actions">
            <button type="button" className="btn btn-primary" onClick={() => void validate()} disabled={checking || !draft.trim()}>{checking ? <><span className="byok-spinner" /> Validating…</> : <><Check size={14} /> Validate Key</>}</button>
            {credential.configured && <button type="button" className="btn" onClick={() => { setEditing(false); setDraft(""); setConsent(false); setValidation(null); }} disabled={checking}>Cancel</button>}
          </div>
        </>}

        {validation && <div className={validationClass} role={validation.kind === "checking" ? "status" : "alert"}><span>{validation.ok || validation.kind === "removed" ? <Check size={15} /> : validation.kind === "checking" ? <span className="byok-spinner" /> : <AlertTriangle size={15} />}</span><span>{validation.message}</span></div>}
        {removeError && <div className="byok-result failure" role="alert"><TriangleAlert size={15} />{removeError}</div>}

        {credential.configured && <div className="byok-saved-actions">
          {!editing && <button type="button" className="btn" onClick={beginChange}><KeyRound size={13} /> Change Key</button>}
          <button type="button" className="btn byok-remove" onClick={remove} disabled={checking}><Trash2 size={13} /> Remove Key</button>
        </div>}
      </section>

      <aside className="byok-side-column">
        <section className="card card-pad byok-side-card">
          <div className="eyebrow">AI PROVIDER</div><h3 style={{ fontSize: 16, marginTop: 7 }}>{providerInfo.label}</h3>
          <p className="mini" style={{ lineHeight: 1.65, marginTop: 8 }}>This is the selected provider for the optional key check. ADAPT's shared Hosted AI key remains server-side and is never sent to your browser.</p>
          <div className="byok-side-status"><span className={`status-dot ${credential.configured ? "is-good" : ""}`} />{credential.configured ? `${providerInfo.label} key verified` : `No ${providerInfo.label} key saved`}</div>
        </section>
        <section className="card card-pad byok-side-card">
          <div className="eyebrow">TUTOR ROUTING</div><h3 style={{ fontSize: 16, marginTop: 7 }}>Your key is not active in Tutor</h3>
          <p className="mini" style={{ lineHeight: 1.65, marginTop: 8 }}>Hosted AI continues to use ADAPT's existing server route. Local AI continues to run on your device. A verified key is stored only for future BYOK support.</p>
          <div className="byok-private-note"><LockKeyhole size={14} /> Key checks go directly to Google. No ADAPT API request is made.</div>
        </section>
      </aside>
    </div>
  </div></AppShell>;
}
